name: Tests
on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    

    steps:
        # - name: Setup node
        #  uses: actions/setup-node@v3
        #  with:
        #    node-version: '18.17.1'
        - name: pwd
          run: echo "$(pwd)"
        - name: ls
          run: echo "$(ls)"
